%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-warehouse-ros-sqlite
Version:        1.0.5
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS warehouse_ros_sqlite package

License:        BSD
URL:            http://ros.org/wiki/warehouse_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jazzy-class-loader
Requires:       ros-jazzy-rclcpp
Requires:       ros-jazzy-sqlite3-vendor
Requires:       ros-jazzy-warehouse-ros
Requires:       ros-jazzy-ros-workspace
BuildRequires:  boost-devel
BuildRequires:  boost-python%{python3_pkgversion}-devel
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-class-loader
BuildRequires:  ros-jazzy-rclcpp
BuildRequires:  ros-jazzy-sqlite3-vendor
BuildRequires:  ros-jazzy-warehouse-ros
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-jazzy-ament-cmake-copyright
BuildRequires:  ros-jazzy-ament-cmake-gtest
BuildRequires:  ros-jazzy-ament-lint-auto >= 0.7.1
BuildRequires:  ros-jazzy-ament-lint-common
BuildRequires:  ros-jazzy-geometry-msgs
%endif

%description
Implementation of warehouse_ros for sqlite

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Mon Sep 02 2024 MoveIt Release Team <moveit_releasers@googlegroups.com> - 1.0.5-1
- Autogenerated by Bloom

* Mon Aug 12 2024 MoveIt Release Team <moveit_releasers@googlegroups.com> - 1.0.4-1
- Autogenerated by Bloom

* Fri Apr 19 2024 MoveIt Release Team <moveit_releasers@googlegroups.com> - 1.0.3-4
- Autogenerated by Bloom

* Wed Mar 06 2024 MoveIt Release Team <moveit_releasers@googlegroups.com> - 1.0.3-3
- Autogenerated by Bloom

